version: '3'

services:
  fullcalendarstore:
    image: fullcalendarstore
    build:
      context: .
      dockerfile: fullcalendarStore/Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    #environment:
    #  CalendarInitialDisplayDate: ''
    #  CalendarProxyFetchUrl: ''
    ports:
      - "8099:80"
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
