version: '3'

services:
  fullcalendarstore:
    image: fullcalendarstore
    build:
      context: .
      dockerfile: fullcalendarStore/Dockerfile
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
